Dialogue view placeholder
esoviscode/discord-dnd-bot pull request #199
Opened 2023-05-09 11:24 UTC by gitesthuman

# Pull request review checklist 📝 ✅

This is a checklist that helps conduct a pull request review properly. These points are required to merge the PR

- [ ] There are no merge conflicts

- [ ] The pull request is named accordingly (description of the functionality - it
   will be visible in the changelog later)
   
- [ ] Every task requirement (from Jira) is done

- [ ] The app runs, it boots up properly (e.g. no syntax errors)

- [ ] The proposed functionality is working properly (you need to pull this branch
   and check for yourself)

- [ ] Each function, class or functionality is properly documented
   (short description of what it does, parameters or return values if they need
   any explanation)

2023-05-10 17:59 UTC, Cellmer requested changes

2023-05-10 17:59 UTC, Cellmer commented on dnd-bot/dnd_bot/dc/ui/views/view_game.py
> +        """ button callback for looting the corpse"""
Niestety dokumentacja niezgodna z przeznaczeniem metody!

2023-05-10 17:59 UTC, Cellmer commented on dnd-bot/dnd_bot/logic/game/handler_dialogue.py
> +        """ handles giving loot for the player and removing the corpse from the world """
Tu także dokumentacja niezgodna z przeznaczeniem metody!!!

2023-05-10 17:59 UTC, Cellmer commented on dnd-bot/dnd_bot/logic/game/initialize_world.py
>  from dnd_bot.logic.prototype.creature import Creature
Nieużywane importy do usunięcia.

2023-05-10 17:59 UTC, Cellmer commented on dnd-bot/dnd_bot/logic/prototype/creature.py
> +        players = [p for p in sum(Multiverse.get_game(self.game_token).entities, []) if isinstance(p, Player)]
Krótkie wyjaśnienie tej linijki w komentarzu by się przydało z uwagi na niecodzienność zapisu.

2023-05-10 18:02 UTC, Cellmer commented
Generalnie piękna sprawa jak dla mnie, drobne poprawki tak jak napisałem.

2023-05-11 08:48 UTC, Silentsky0 submitted a review, later dismissed
![image](https://github.com/esoviscode/discord-dnd-bot/assets/81694867/f937eeac-2715-437b-ae0f-0a5a50154824)
![image](https://github.com/esoviscode/discord-dnd-bot/assets/81694867/ac21fc92-a334-485a-bdca-8c03425295ab)


Nie wybierając nikogo do pogadania wyrzucany jest błąd. Bardzo prosta poprawka polegająca na wyrzuceniu wyjątku i wypisanie jakiegoś error_dm_message

2023-05-12 20:56 UTC, gitesthuman commented on dnd-bot/dnd_bot/logic/game/initialize_world.py
>  from dnd_bot.logic.prototype.creature import Creature
dzbanem jesteś i nie czytasz commitów
![image](https://github.com/esoviscode/discord-dnd-bot/assets/90265591/40f5182c-eb2a-4956-baf8-3e838a8a7062)
są potrzebne do tego

2023-05-15 14:22 UTC, merged